from __future__ import annotations
from typing import Dict, Optional

"""Sport-scoped alias helpers for team resolution.

TEAM_ALIASES contains only globally unambiguous aliases so lookups no longer
silently overwrite cross-sport names like "giants" or "cardinals".
Use resolve_team_alias(..., sport=...) when sport context is available.
"""

TEAM_ALIASES_BY_SPORT: Dict[str, Dict[str, str]] = {
    "nfl": {
        "arizona": "ARI",
        "arizona cardinals": "ARI",
        "cardinals": "ARI",
        "atlanta": "ATL",
        "atlanta falcons": "ATL",
        "falcons": "ATL",
        "baltimore": "BAL",
        "baltimore ravens": "BAL",
        "ravens": "BAL",
        "buffalo": "BUF",
        "buffalo bills": "BUF",
        "bills": "BUF",
        "carolina": "CAR",
        "carolina panthers": "CAR",
        "panthers": "CAR",
        "chicago": "CHI",
        "chicago bears": "CHI",
        "bears": "CHI",
        "cincinnati": "CIN",
        "cincinnati bengals": "CIN",
        "bengals": "CIN",
        "cleveland": "CLE",
        "cleveland browns": "CLE",
        "browns": "CLE",
        "dallas": "DAL",
        "dallas cowboys": "DAL",
        "cowboys": "DAL",
        "denver": "DEN",
        "denver broncos": "DEN",
        "broncos": "DEN",
        "detroit": "DET",
        "detroit lions": "DET",
        "lions": "DET",
        "green bay": "GB",
        "green bay packers": "GB",
        "packers": "GB",
        "houston": "HOU",
        "houston texans": "HOU",
        "texans": "HOU",
        "indianapolis": "IND",
        "indianapolis colts": "IND",
        "colts": "IND",
        "jacksonville": "JAX",
        "jacksonville jaguars": "JAX",
        "jaguars": "JAX",
        "jags": "JAX",
        "kansas city": "KC",
        "kansas city chiefs": "KC",
        "chiefs": "KC",
        "las vegas": "LV",
        "las vegas raiders": "LV",
        "raiders": "LV",
        "oakland raiders": "LV",
        "los angeles raiders": "LV",
        "los angeles chargers": "LAC",
        "la chargers": "LAC",
        "chargers": "LAC",
        "san diego chargers": "LAC",
        "los angeles rams": "LAR",
        "la rams": "LAR",
        "rams": "LAR",
        "st. louis rams": "LAR",
        "st louis rams": "LAR",
        "miami": "MIA",
        "miami dolphins": "MIA",
        "dolphins": "MIA",
        "minnesota": "MIN",
        "minnesota vikings": "MIN",
        "vikings": "MIN",
        "new england": "NE",
        "new england patriots": "NE",
        "patriots": "NE",
        "pats": "NE",
        "new orleans": "NO",
        "new orleans saints": "NO",
        "saints": "NO",
        "new york giants": "NYG",
        "ny giants": "NYG",
        "giants": "NYG",
        "new york jets": "NYJ",
        "ny jets": "NYJ",
        "jets": "NYJ",
        "philadelphia": "PHI",
        "philadelphia eagles": "PHI",
        "eagles": "PHI",
        "pittsburgh": "PIT",
        "pittsburgh steelers": "PIT",
        "steelers": "PIT",
        "san francisco": "SF",
        "san francisco 49ers": "SF",
        "49ers": "SF",
        "niners": "SF",
        "seattle": "SEA",
        "seattle seahawks": "SEA",
        "seahawks": "SEA",
        "tampa bay": "TB",
        "tampa bay buccaneers": "TB",
        "buccaneers": "TB",
        "bucs": "TB",
        "tennessee": "TEN",
        "tennessee titans": "TEN",
        "titans": "TEN",
        "houston oilers": "TEN",
        "washington": "WAS",
        "washington commanders": "WAS",
        "commanders": "WAS",
        "washington football team": "WAS",
        "washington redskins": "WAS",
    },
    "nba": {
        "atlanta hawks": "ATL",
        "hawks": "ATL",
        "boston celtics": "BOS",
        "celtics": "BOS",
        "brooklyn nets": "BKN",
        "nets": "BKN",
        "new jersey nets": "BKN",
        "charlotte hornets": "CHA",
        "hornets": "CHA",
        "chicago bulls": "CHI",
        "bulls": "CHI",
        "cleveland cavaliers": "CLE",
        "cavaliers": "CLE",
        "cavs": "CLE",
        "dallas mavericks": "DAL",
        "mavericks": "DAL",
        "mavs": "DAL",
        "denver nuggets": "DEN",
        "nuggets": "DEN",
        "detroit pistons": "DET",
        "pistons": "DET",
        "golden state warriors": "GSW",
        "warriors": "GSW",
        "houston rockets": "HOU",
        "rockets": "HOU",
        "indiana pacers": "IND",
        "pacers": "IND",
        "la clippers": "LAC",
        "los angeles clippers": "LAC",
        "clippers": "LAC",
        "la lakers": "LAL",
        "los angeles lakers": "LAL",
        "lakers": "LAL",
        "memphis grizzlies": "MEM",
        "grizzlies": "MEM",
        "miami heat": "MIA",
        "heat": "MIA",
        "milwaukee bucks": "MIL",
        "bucks": "MIL",
        "minnesota timberwolves": "MIN",
        "timberwolves": "MIN",
        "wolves": "MIN",
        "new orleans pelicans": "NOP",
        "pelicans": "NOP",
        "new york knicks": "NYK",
        "ny knicks": "NYK",
        "knicks": "NYK",
        "oklahoma city thunder": "OKC",
        "thunder": "OKC",
        "seattle supersonics": "OKC",
        "orlando magic": "ORL",
        "magic": "ORL",
        "philadelphia 76ers": "PHI",
        "76ers": "PHI",
        "sixers": "PHI",
        "phoenix suns": "PHX",
        "suns": "PHX",
        "suns'": "PHX",
        "phoenix": "PHX",
        "portland trail blazers": "POR",
        "trail blazers": "POR",
        "blazers": "POR",
        "sacramento kings": "SAC",
        "kings": "SAC",
        "san antonio spurs": "SAS",
        "spurs": "SAS",
        "toronto raptors": "TOR",
        "raptors": "TOR",
        "utah jazz": "UTA",
        "jazz": "UTA",
        "washington wizards": "WAS",
        "wizards": "WAS",
    },
    "mlb": {
        "arizona diamondbacks": "ARI",
        "diamondbacks": "ARI",
        "d-backs": "ARI",
        "dbacks": "ARI",
        "atlanta braves": "ATL",
        "braves": "ATL",
        "baltimore orioles": "BAL",
        "orioles": "BAL",
        "o's": "BAL",
        "os": "BAL",
        "boston red sox": "BOS",
        "red sox": "BOS",
        "chicago cubs": "CHC",
        "cubs": "CHC",
        "chicago white sox": "CWS",
        "white sox": "CWS",
        "cincinnati reds": "CIN",
        "reds": "CIN",
        "cleveland guardians": "CLE",
        "guardians": "CLE",
        "cleveland indians": "CLE",
        "colorado rockies": "COL",
        "rockies": "COL",
        "detroit tigers": "DET",
        "tigers": "DET",
        "houston astros": "HOU",
        "astros": "HOU",
        "kansas city royals": "KC",
        "royals": "KC",
        "los angeles angels": "LAA",
        "la angels": "LAA",
        "angels": "LAA",
        "anaheim angels": "LAA",
        "los angeles angels of anaheim": "LAA",
        "los angeles dodgers": "LAD",
        "la dodgers": "LAD",
        "dodgers": "LAD",
        "miami marlins": "MIA",
        "marlins": "MIA",
        "florida marlins": "MIA",
        "milwaukee brewers": "MIL",
        "brewers": "MIL",
        "minnesota twins": "MIN",
        "twins": "MIN",
        "new york mets": "NYM",
        "ny mets": "NYM",
        "mets": "NYM",
        "new york yankees": "NYY",
        "ny yankees": "NYY",
        "yankees": "NYY",
        "oakland athletics": "OAK",
        "athletics": "OAK",
        "a's": "OAK",
        "as": "OAK",
        "oakland a's": "OAK",
        "philadelphia phillies": "PHI",
        "phillies": "PHI",
        "pittsburgh pirates": "PIT",
        "pirates": "PIT",
        "san diego padres": "SD",
        "padres": "SD",
        "san francisco giants": "SF",
        "sf giants": "SF",
        "giants": "SF",
        "san fran giants": "SF",
        "seattle mariners": "SEA",
        "mariners": "SEA",
        "st. louis cardinals": "STL",
        "st louis cardinals": "STL",
        "cardinals": "STL",
        "cards": "STL",
        "tampa bay rays": "TB",
        "rays": "TB",
        "tampa bay devil rays": "TB",
        "devil rays": "TB",
        "texas rangers": "TEX",
        "rangers": "TEX",
        "toronto blue jays": "TOR",
        "blue jays": "TOR",
        "jays": "TOR",
        "washington nationals": "WSH",
        "nationals": "WSH",
        "nats": "WSH",
        "montreal expos": "WSH",
    },
    "cfb": {
        "alabama": "BAMA",
        "crimson tide": "BAMA",
        "bama": "BAMA",
        "georgia": "UGA",
        "bulldogs": "UGA",
        "uga": "UGA",
        "ohio state": "OSU",
        "buckeyes": "OSU",
        "osu": "OSU",
        "michigan": "MICH",
        "wolverines": "MICH",
        "penn state": "PSU",
        "nittany lions": "PSU",
        "psu": "PSU",
        "notre dame": "ND",
        "fighting irish": "ND",
        "lsu": "LSU",
        "tigers": "LSU",
        "clemson": "CLEM",
        "clemson tigers": "CLEM",
        "florida state": "FSU",
        "seminoles": "FSU",
        "fsu": "FSU",
        "florida gators": "FLA",
        "florida": "FLA",
        "gators": "FLA",
        "miami hurricanes": "MIA_CFB",
        "miami": "MIA_CFB",
        "hurricanes": "MIA_CFB",
        "the u": "MIA_CFB",
        "usc": "USC",
        "southern cal": "USC",
        "southern california": "USC",
        "trojans": "USC",
        "ucla": "UCLA",
        "bruins": "UCLA",
        "texas": "TEX_CFB",
        "longhorns": "TEX_CFB",
        "ut austin": "TEX_CFB",
        "oklahoma": "OU",
        "sooners": "OU",
        "ou": "OU",
        "texas a&m": "TAMU",
        "texas am": "TAMU",
        "aggies": "TAMU",
        "tamu": "TAMU",
        "oregon": "ORE",
        "ducks": "ORE",
        "washington": "UW",
        "huskies": "UW",
        "utah": "UTAH",
        "utes": "UTAH",
        "tcu": "TCU",
        "horned frogs": "TCU",
        "baylor": "BAY",
        "bears": "BAY",
        "oklahoma state": "OKST",
        "cowboys": "OKST",
        "okst": "OKST",
        "kansas state": "KSU",
        "wildcats": "KSU",
        "kansas": "KU",
        "jayhawks": "KU",
        "iowa": "IOWA",
        "hawkeyes": "IOWA",
        "iowa state": "ISU",
        "cyclones": "ISU",
        "wisconsin": "WISC",
        "badgers": "WISC",
        "nebraska": "NEB",
        "cornhuskers": "NEB",
        "huskers": "NEB",
        "minnesota": "MINN",
        "golden gophers": "MINN",
        "gophers": "MINN",
        "michigan state": "MSU",
        "spartans": "MSU",
        "msu": "MSU",
        "indiana": "IND_CFB",
        "hoosiers": "IND_CFB",
        "purdue": "PUR",
        "boilermakers": "PUR",
        "northwestern": "NW",
        "illinois": "ILL",
        "fighting illini": "ILL",
        "maryland": "MD",
        "terrapins": "MD",
        "terps": "MD",
        "rutgers": "RUTG",
        "scarlet knights": "RUTG",
        "tennessee": "TENN",
        "volunteers": "TENN",
        "vols": "TENN",
        "auburn": "AUB",
        "auburn tigers": "AUB",
        "ole miss": "MISS",
        "mississippi": "MISS",
        "rebels": "MISS",
        "mississippi state": "MSST",
        "kentucky": "UK",
        "south carolina": "SCAR",
        "gamecocks": "SCAR",
        "arkansas": "ARK",
        "razorbacks": "ARK",
        "hogs": "ARK",
        "missouri": "MIZ",
        "vanderbilt": "VAND",
        "commodores": "VAND",
        "dores": "VAND",
        "north carolina": "UNC",
        "tar heels": "UNC",
        "duke": "DUKE",
        "blue devils": "DUKE",
        "nc state": "NCSU",
        "north carolina state": "NCSU",
        "wolfpack": "NCSU",
        "virginia tech": "VT",
        "hokies": "VT",
        "virginia": "UVA",
        "cavaliers": "UVA",
        "hoos": "UVA",
        "georgia tech": "GT",
        "yellow jackets": "GT",
        "syracuse": "SYR",
        "orange": "SYR",
        "pitt": "PITT",
        "pittsburgh": "PITT",
        "panthers": "PITT",
        "west virginia": "WVU",
        "mountaineers": "WVU",
        "louisville": "LOU",
        "cardinals": "LOU",
        "ucf": "UCF",
        "central florida": "UCF",
        "knights": "UCF",
        "cincinnati": "CIN_CFB",
        "bearcats": "CIN_CFB",
        "byu": "BYU",
        "brigham young": "BYU",
        "cougars": "BYU",
    },
}

TEAM_ALIASES: Dict[str, str] = {
    "arizona": "ARI",
    "arizona cardinals": "ARI",
    "atlanta": "ATL",
    "atlanta falcons": "ATL",
    "falcons": "ATL",
    "baltimore": "BAL",
    "baltimore ravens": "BAL",
    "ravens": "BAL",
    "buffalo": "BUF",
    "buffalo bills": "BUF",
    "bills": "BUF",
    "carolina": "CAR",
    "carolina panthers": "CAR",
    "chicago": "CHI",
    "chicago bears": "CHI",
    "cincinnati bengals": "CIN",
    "bengals": "CIN",
    "cleveland": "CLE",
    "cleveland browns": "CLE",
    "browns": "CLE",
    "dallas": "DAL",
    "dallas cowboys": "DAL",
    "denver": "DEN",
    "denver broncos": "DEN",
    "broncos": "DEN",
    "detroit": "DET",
    "detroit lions": "DET",
    "lions": "DET",
    "green bay": "GB",
    "green bay packers": "GB",
    "packers": "GB",
    "houston": "HOU",
    "houston texans": "HOU",
    "texans": "HOU",
    "indianapolis": "IND",
    "indianapolis colts": "IND",
    "colts": "IND",
    "jacksonville": "JAX",
    "jacksonville jaguars": "JAX",
    "jaguars": "JAX",
    "jags": "JAX",
    "kansas city": "KC",
    "kansas city chiefs": "KC",
    "chiefs": "KC",
    "las vegas": "LV",
    "las vegas raiders": "LV",
    "raiders": "LV",
    "oakland raiders": "LV",
    "los angeles raiders": "LV",
    "los angeles chargers": "LAC",
    "la chargers": "LAC",
    "chargers": "LAC",
    "san diego chargers": "LAC",
    "los angeles rams": "LAR",
    "la rams": "LAR",
    "rams": "LAR",
    "st. louis rams": "LAR",
    "st louis rams": "LAR",
    "miami dolphins": "MIA",
    "dolphins": "MIA",
    "minnesota vikings": "MIN",
    "vikings": "MIN",
    "new england": "NE",
    "new england patriots": "NE",
    "patriots": "NE",
    "pats": "NE",
    "new orleans": "NO",
    "new orleans saints": "NO",
    "saints": "NO",
    "new york giants": "NYG",
    "ny giants": "NYG",
    "new york jets": "NYJ",
    "ny jets": "NYJ",
    "jets": "NYJ",
    "philadelphia": "PHI",
    "philadelphia eagles": "PHI",
    "eagles": "PHI",
    "pittsburgh steelers": "PIT",
    "steelers": "PIT",
    "san francisco": "SF",
    "san francisco 49ers": "SF",
    "49ers": "SF",
    "niners": "SF",
    "seattle": "SEA",
    "seattle seahawks": "SEA",
    "seahawks": "SEA",
    "tampa bay": "TB",
    "tampa bay buccaneers": "TB",
    "buccaneers": "TB",
    "bucs": "TB",
    "tennessee titans": "TEN",
    "titans": "TEN",
    "houston oilers": "TEN",
    "washington commanders": "WAS",
    "commanders": "WAS",
    "washington football team": "WAS",
    "washington redskins": "WAS",
    "atlanta hawks": "ATL",
    "hawks": "ATL",
    "boston celtics": "BOS",
    "celtics": "BOS",
    "brooklyn nets": "BKN",
    "nets": "BKN",
    "new jersey nets": "BKN",
    "charlotte hornets": "CHA",
    "hornets": "CHA",
    "chicago bulls": "CHI",
    "bulls": "CHI",
    "cleveland cavaliers": "CLE",
    "cavs": "CLE",
    "dallas mavericks": "DAL",
    "mavericks": "DAL",
    "mavs": "DAL",
    "denver nuggets": "DEN",
    "nuggets": "DEN",
    "detroit pistons": "DET",
    "pistons": "DET",
    "golden state warriors": "GSW",
    "warriors": "GSW",
    "houston rockets": "HOU",
    "rockets": "HOU",
    "indiana pacers": "IND",
    "pacers": "IND",
    "la clippers": "LAC",
    "los angeles clippers": "LAC",
    "clippers": "LAC",
    "la lakers": "LAL",
    "los angeles lakers": "LAL",
    "lakers": "LAL",
    "memphis grizzlies": "MEM",
    "grizzlies": "MEM",
    "miami heat": "MIA",
    "heat": "MIA",
    "milwaukee bucks": "MIL",
    "bucks": "MIL",
    "minnesota timberwolves": "MIN",
    "timberwolves": "MIN",
    "wolves": "MIN",
    "new orleans pelicans": "NOP",
    "pelicans": "NOP",
    "new york knicks": "NYK",
    "ny knicks": "NYK",
    "knicks": "NYK",
    "oklahoma city thunder": "OKC",
    "thunder": "OKC",
    "seattle supersonics": "OKC",
    "orlando magic": "ORL",
    "magic": "ORL",
    "philadelphia 76ers": "PHI",
    "76ers": "PHI",
    "sixers": "PHI",
    "phoenix suns": "PHX",
    "suns": "PHX",
    "suns'": "PHX",
    "phoenix": "PHX",
    "portland trail blazers": "POR",
    "trail blazers": "POR",
    "blazers": "POR",
    "sacramento kings": "SAC",
    "kings": "SAC",
    "san antonio spurs": "SAS",
    "spurs": "SAS",
    "toronto raptors": "TOR",
    "raptors": "TOR",
    "utah jazz": "UTA",
    "jazz": "UTA",
    "washington wizards": "WAS",
    "wizards": "WAS",
    "arizona diamondbacks": "ARI",
    "diamondbacks": "ARI",
    "d-backs": "ARI",
    "dbacks": "ARI",
    "atlanta braves": "ATL",
    "braves": "ATL",
    "baltimore orioles": "BAL",
    "orioles": "BAL",
    "o's": "BAL",
    "os": "BAL",
    "boston red sox": "BOS",
    "red sox": "BOS",
    "chicago cubs": "CHC",
    "cubs": "CHC",
    "chicago white sox": "CWS",
    "white sox": "CWS",
    "cincinnati reds": "CIN",
    "reds": "CIN",
    "cleveland guardians": "CLE",
    "guardians": "CLE",
    "cleveland indians": "CLE",
    "colorado rockies": "COL",
    "rockies": "COL",
    "detroit tigers": "DET",
    "houston astros": "HOU",
    "astros": "HOU",
    "kansas city royals": "KC",
    "royals": "KC",
    "los angeles angels": "LAA",
    "la angels": "LAA",
    "angels": "LAA",
    "anaheim angels": "LAA",
    "los angeles angels of anaheim": "LAA",
    "los angeles dodgers": "LAD",
    "la dodgers": "LAD",
    "dodgers": "LAD",
    "miami marlins": "MIA",
    "marlins": "MIA",
    "florida marlins": "MIA",
    "milwaukee brewers": "MIL",
    "brewers": "MIL",
    "minnesota twins": "MIN",
    "twins": "MIN",
    "new york mets": "NYM",
    "ny mets": "NYM",
    "mets": "NYM",
    "new york yankees": "NYY",
    "ny yankees": "NYY",
    "yankees": "NYY",
    "oakland athletics": "OAK",
    "athletics": "OAK",
    "a's": "OAK",
    "as": "OAK",
    "oakland a's": "OAK",
    "philadelphia phillies": "PHI",
    "phillies": "PHI",
    "pittsburgh pirates": "PIT",
    "pirates": "PIT",
    "san diego padres": "SD",
    "padres": "SD",
    "san francisco giants": "SF",
    "sf giants": "SF",
    "san fran giants": "SF",
    "seattle mariners": "SEA",
    "mariners": "SEA",
    "st. louis cardinals": "STL",
    "st louis cardinals": "STL",
    "cards": "STL",
    "tampa bay rays": "TB",
    "rays": "TB",
    "tampa bay devil rays": "TB",
    "devil rays": "TB",
    "texas rangers": "TEX",
    "rangers": "TEX",
    "toronto blue jays": "TOR",
    "blue jays": "TOR",
    "jays": "TOR",
    "washington nationals": "WSH",
    "nationals": "WSH",
    "nats": "WSH",
    "montreal expos": "WSH",
    "alabama": "BAMA",
    "crimson tide": "BAMA",
    "bama": "BAMA",
    "georgia": "UGA",
    "uga": "UGA",
    "ohio state": "OSU",
    "buckeyes": "OSU",
    "osu": "OSU",
    "michigan": "MICH",
    "wolverines": "MICH",
    "penn state": "PSU",
    "nittany lions": "PSU",
    "psu": "PSU",
    "notre dame": "ND",
    "fighting irish": "ND",
    "lsu": "LSU",
    "clemson": "CLEM",
    "clemson tigers": "CLEM",
    "florida state": "FSU",
    "seminoles": "FSU",
    "fsu": "FSU",
    "florida gators": "FLA",
    "florida": "FLA",
    "gators": "FLA",
    "miami hurricanes": "MIA_CFB",
    "hurricanes": "MIA_CFB",
    "the u": "MIA_CFB",
    "usc": "USC",
    "southern cal": "USC",
    "southern california": "USC",
    "trojans": "USC",
    "ucla": "UCLA",
    "bruins": "UCLA",
    "texas": "TEX_CFB",
    "longhorns": "TEX_CFB",
    "ut austin": "TEX_CFB",
    "oklahoma": "OU",
    "sooners": "OU",
    "ou": "OU",
    "texas a&m": "TAMU",
    "texas am": "TAMU",
    "aggies": "TAMU",
    "tamu": "TAMU",
    "oregon": "ORE",
    "ducks": "ORE",
    "huskies": "UW",
    "utah": "UTAH",
    "utes": "UTAH",
    "tcu": "TCU",
    "horned frogs": "TCU",
    "baylor": "BAY",
    "oklahoma state": "OKST",
    "okst": "OKST",
    "kansas state": "KSU",
    "kansas": "KU",
    "jayhawks": "KU",
    "iowa": "IOWA",
    "hawkeyes": "IOWA",
    "iowa state": "ISU",
    "cyclones": "ISU",
    "wisconsin": "WISC",
    "badgers": "WISC",
    "nebraska": "NEB",
    "cornhuskers": "NEB",
    "huskers": "NEB",
    "golden gophers": "MINN",
    "gophers": "MINN",
    "michigan state": "MSU",
    "spartans": "MSU",
    "msu": "MSU",
    "indiana": "IND_CFB",
    "hoosiers": "IND_CFB",
    "purdue": "PUR",
    "boilermakers": "PUR",
    "northwestern": "NW",
    "illinois": "ILL",
    "fighting illini": "ILL",
    "maryland": "MD",
    "terrapins": "MD",
    "terps": "MD",
    "rutgers": "RUTG",
    "scarlet knights": "RUTG",
    "volunteers": "TENN",
    "vols": "TENN",
    "auburn": "AUB",
    "auburn tigers": "AUB",
    "ole miss": "MISS",
    "mississippi": "MISS",
    "rebels": "MISS",
    "mississippi state": "MSST",
    "kentucky": "UK",
    "south carolina": "SCAR",
    "gamecocks": "SCAR",
    "arkansas": "ARK",
    "razorbacks": "ARK",
    "hogs": "ARK",
    "missouri": "MIZ",
    "vanderbilt": "VAND",
    "commodores": "VAND",
    "dores": "VAND",
    "north carolina": "UNC",
    "tar heels": "UNC",
    "duke": "DUKE",
    "blue devils": "DUKE",
    "nc state": "NCSU",
    "north carolina state": "NCSU",
    "wolfpack": "NCSU",
    "virginia tech": "VT",
    "hokies": "VT",
    "virginia": "UVA",
    "hoos": "UVA",
    "georgia tech": "GT",
    "yellow jackets": "GT",
    "syracuse": "SYR",
    "orange": "SYR",
    "pitt": "PITT",
    "west virginia": "WVU",
    "mountaineers": "WVU",
    "louisville": "LOU",
    "ucf": "UCF",
    "central florida": "UCF",
    "knights": "UCF",
    "bearcats": "CIN_CFB",
    "byu": "BYU",
    "brigham young": "BYU",
    "cougars": "BYU",
}

AMBIGUOUS_TEAM_ALIASES: Dict[str, list[str]] = {
    "bears": ["BAY", "CHI"],
    "bulldogs": ["MSST", "UGA"],
    "cardinals": ["ARI", "LOU", "STL"],
    "cavaliers": ["CLE", "UVA"],
    "cincinnati": ["CIN", "CIN_CFB"],
    "cowboys": ["DAL", "OKST"],
    "giants": ["NYG", "SF"],
    "miami": ["MIA", "MIA_CFB"],
    "minnesota": ["MIN", "MINN"],
    "panthers": ["CAR", "PITT"],
    "pittsburgh": ["PIT", "PITT"],
    "tennessee": ["TEN", "TENN"],
    "tigers": ["DET", "LSU", "MIZ"],
    "washington": ["UW", "WAS"],
    "wildcats": ["KSU", "NW", "UK"],
}

def normalize_alias(value: str) -> str:
    return " ".join((value or "").lower().strip().split())

def aliases_for_sport(sport: str | None) -> Dict[str, str]:
    key = normalize_alias(sport or "")
    return TEAM_ALIASES_BY_SPORT.get(key, TEAM_ALIASES)

def resolve_team_alias(alias: str, sport: str | None = None) -> Optional[str]:
    normalized = normalize_alias(alias)
    if not normalized:
        return None
    sport_map = aliases_for_sport(sport)
    return sport_map.get(normalized) or TEAM_ALIASES.get(normalized)

__all__ = [
    "TEAM_ALIASES",
    "TEAM_ALIASES_BY_SPORT",
    "AMBIGUOUS_TEAM_ALIASES",
    "aliases_for_sport",
    "normalize_alias",
    "resolve_team_alias",
]
