"""add ingest_runs

Revision ID: 462fcc3bda2f
Revises: ca40486b89bc
Create Date: 2026-01-15 11:29:31.244987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462fcc3bda2f'
down_revision: Union[str, None] = 'ca40486b89bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_runs_started_at'), 'ingest_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_ingest_runs_status'), 'ingest_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_runs_status'), table_name='ingest_runs')
    op.drop_index(op.f('ix_ingest_runs_started_at'), table_name='ingest_runs')
    op.drop_table('ingest_runs')
    # ### end Alembic commands ###
