"""init schema

Revision ID: ca40486b89bc
Revises: 
Create Date: 2026-01-15 10:49:55.889492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca40486b89bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('sport', sa.String(length=30), nullable=False),
    sa.Column('team', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_created_at'), 'content_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_items_published_at'), 'content_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_items_source'), 'content_items', ['source'], unique=False)
    op.create_index(op.f('ix_content_items_sport'), 'content_items', ['sport'], unique=False)
    op.create_index(op.f('ix_content_items_team'), 'content_items', ['team'], unique=False)
    op.create_index(op.f('ix_content_items_url'), 'content_items', ['url'], unique=True)
    op.create_index('ix_content_sport_published', 'content_items', ['sport', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_sport_published', table_name='content_items')
    op.drop_index(op.f('ix_content_items_url'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_team'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_sport'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_source'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_published_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_created_at'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
